### ISSUE TITLE
Ajuste margens e paddings

### ISSUE THREAD

**Issue by nncl** [dindigital/Din-Style#10]
Giungla:

``` css
.p-h-10 {
  padding-left: 10px;
  padding-right: 10px;
}
```
