### ISSUE TITLE
Incluir classe flex

### ISSUE THREAD

**Issue by nncl** [dindigital/Din-Style#4]
Adicionar a seguinte classe para centralização de conteúdos verticalmente:

``` css
.dd-center-h-v {
  display: -webkit-flex;
    display: -webkit-box;
    display: -ms-flexbox;
    display: flex;
    -webkit-box-align: center;
        -ms-flex-align: center;
            align-items: center;
    -webkit-align-items: center;
    -webkit-box-pack: center;
        -ms-flex-pack: center;
            justify-content: center;
    -webkit-justify-content: center;
    -webkit-box-orient: vertical;
    -webkit-box-direction: normal;
        -ms-flex-direction: column;
            flex-direction: column;
    -webkit-flex-direction: column;
}
```
