### ISSUE TITLE
Tratar CSS de CK

### ISSUE THREAD

**Issue by nncl** [dindigital/Din-Style#5]
Resetar CSS da classe `.dd-ck-content` no Din Style e no projeto em si sobrescrever e acordo com o layout. Exemplo:

Din Style, **style.scss**:

``` scss
.dd-ck-content {
 h1, h2 {
  clear: both;
 }
}
```

Em um projeto específico:

``` scss
.dd-ck-content h1 {
  color: $main;
}
```

E no projeto utilizamos essa classe na estrutura a ser integrada pelo backend:

``` html
<div class="dd-ck-content">
  {{$content}}
</div>
```

O WordPress [faz o mesmo](https://codex.wordpress.org/CSS) disponibilizando para os desenvolvedores um _starter_.

O que acha, @Fnks ?
